# Generated by Django 3.2 on 2022-11-02 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
