# Generated by Django 3.2 on 2022-11-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0003_alter_blacklist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Firstname в телеграмм'),
        ),
    ]
