# Generated by Django 3.2 on 2022-11-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0004_blacklist_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='messages_id',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
