# Generated by Django 3.2 on 2022-11-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0005_alter_chathistory_messages_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='user_firstname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Никнейм пользователя'),
        ),
    ]
