# Generated by Django 3.2 on 2022-11-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0006_chathistory_user_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='text',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
