# Generated by Django 3.2 on 2022-11-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0007_alter_chathistory_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время урока')),
                ('lesson', models.CharField(max_length=50, verbose_name='Урок')),
                ('teacher', models.CharField(blank=True, max_length=150, null=True, verbose_name='Учитель')),
                ('comments', models.CharField(blank=True, max_length=150, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Расписание',
                'ordering': ('-date',),
            },
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='blacklist',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='userbot',
        ),
        migrations.RemoveField(
            model_name='userbot',
            name='proxy',
        ),
        migrations.DeleteModel(
            name='BlackList',
        ),
        migrations.DeleteModel(
            name='Chats',
        ),
        migrations.DeleteModel(
            name='Proxy',
        ),
        migrations.DeleteModel(
            name='UserBot',
        ),
    ]
