# Generated by Django 3.2 on 2022-11-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0008_auto_20221109_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedule',
            name='day',
            field=models.CharField(choices=[('Moday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wethday', 'Среда'), ('chetverg', 'Четверг'), ('Fryday', 'Пятница')], default=10.0, max_length=10),
            preserve_default=False,
        ),
    ]
