# Generated by Django 3.2 on 2022-11-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0009_shedule_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shedule',
            options={'ordering': ('-day',), 'verbose_name': 'Расписание'},
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='date',
        ),
        migrations.AlterField(
            model_name='shedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
