# Generated by Django 3.2 on 2022-11-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0010_auto_20221109_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedule',
            name='time',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
