# Generated by Django 3.2 on 2022-11-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0011_shedule_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shedule',
            options={'ordering': ('-day', 'time'), 'verbose_name': 'Расписание'},
        ),
        migrations.AlterField(
            model_name='shedule',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
