# Generated by Django 3.2 on 2022-11-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0014_auto_20221109_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.ManyToManyField(to='userbot.Time_lesson'),
        ),
    ]
