# Generated by Django 3.2 on 2022-11-09 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0016_auto_20221109_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day_lesson',
            options={'ordering': ('day',), 'verbose_name': 'День недели'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='day',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='time',
        ),
        migrations.AddField(
            model_name='day_lesson',
            name='lesson',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='userbot.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day_lesson',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day_lesson',
            name='day',
            field=models.CharField(choices=[('Mn', 'Понедельник'), ('Tu', 'Вторник'), ('We', 'Среда'), ('Th', 'Четверг'), ('Fr', 'Пятница')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.OneToOneField(default=1000, on_delete=django.db.models.deletion.CASCADE, to='userbot.teacher_lesson'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Time_lesson',
        ),
    ]
