# Generated by Django 3.2 on 2022-11-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0020_shedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shedule',
        ),
    ]
