# Generated by Django 3.2 on 2022-11-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0021_delete_shedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day_lesson',
            old_name='time',
            new_name='time_from',
        ),
        migrations.AddField(
            model_name='day_lesson',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
