# Generated by Django 3.2 on 2022-11-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0022_auto_20221111_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day_lesson',
            options={'ordering': ('time_from',), 'verbose_name': 'День недели'},
        ),
        migrations.AlterField(
            model_name='day_lesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='userbot.lesson'),
        ),
    ]
