# Generated by Django 3.2 on 2022-11-15 06:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0024_alter_day_lesson_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=3000, verbose_name='Вопрос')),
                ('question_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('question_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='day_lesson',
            options={'ordering': ('time_from',), 'verbose_name': 'День недели', 'verbose_name_plural': 'Дени недели'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='teacher_lesson',
            options={'ordering': ('teacher',), 'verbose_name': 'Учител', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=3000, verbose_name='Ответ')),
                ('answer_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userbot.question')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ('answer_date',),
            },
        ),
    ]
