# Generated by Django 3.2 on 2022-11-15 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0025_auto_20221115_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day_lesson',
            options={'ordering': ('time_from',), 'verbose_name': 'День недели', 'verbose_name_plural': 'Дни недели'},
        ),
        migrations.AlterField(
            model_name='question',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Дата вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tg_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
