# Generated by Django 3.2 on 2022-11-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0026_auto_20221115_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answered',
            field=models.BooleanField(default=False, verbose_name='Ответ'),
        ),
    ]
