# Generated by Django 3.2 on 2022-11-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0027_question_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='message_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
