# Generated by Django 3.2 on 2023-01-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0029_alter_question_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answered',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ответ'),
        ),
    ]
