# Generated by Django 3.2 on 2022-10-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tg_name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
