# Generated by Django 3.2 on 2022-11-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(default=1000, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_push_maker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_respondent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(default=2000, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='number',
            field=models.CharField(default=50621231, max_length=20),
            preserve_default=False,
        ),
    ]
